name = "The Rose Garden"
author = "SugoiDogo"
version = "6.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1b922f6fd2fba46db4b2777f30fe1c64f71556160d670b96969b8fcdf65472c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
