name = "RoseGarden"
author = "sugoidogo"
version = "10.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "943de5808b48bceb4283d69a4f07d81b2e7366517de53ed9bf4fb314e8a2f61e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
